### ISSUE TITLE
Use the model to predict entity alignment

### ISSUE THREAD

**Issue by fwhite73** [1049451037/HIN-Align#1]
Hi! Thanks for the good work you shared with us.

I was wondering how this model could be used to make predictions on some other knowledge graphs pairs.

Thank you.

**Comment by 1049451037** [comment]
You can fit your data to the same format as my model input. Since my method is supervised, you may need to prepare some aligned nodes for two graphs.

**Comment by 1049451037** [comment]
If you mean using my trained model to do zero-shot inference on other graph, I think it's not available because different graph has different node feature space...

**Comment by fwhite73** [comment]
Ok so it will always be necessary to train the model on every graph structure... but the model can utilize some attributes not present in the training data? Or the training data has to specify all the possible attributes for the entities?

Lastly, the predict method for the GCN_Align model would be implemented as the one in the simple GCN?

**Comment by 1049451037** [comment]
`Case 1`:

If you have two graph pairs with nodes attributes in the same space, you can just train pair one (G1, G2), and then make prediction on pair two (G3, G4). It works fine I think.

`Case 2`:

If you have two graph pairs, but their node attributes are not same, I don't think the trained model can transfer well... However, since my method is an old method (born in 2018), there may be some more advanced methods, some are even unsupervised, and some can transfer structure-related knowledge. But I didn't follow this area recently, I'm not quite familiar with them.

`Last`:

For the predict method, GCN_Align just return self.outputs as node features.

**Comment by fwhite73** [comment]
Ok, then.

I think I will test it. In case I will let you know.

Thanks again.
